05-04-2020 (#47)
* :construction_worker: GitHub Actiions Maven default
Fix #7

* :construction_worker: GitHub Actions Maven default
Fix #7

* :construction_worker: Séparation des stages en job

* Ajout de maven-dependency-plugin (#32)

* :heavy_plus_sign: maven-dependency-plugin

* :pushpin: maven-dependency-plugin fix version
Add org.junit.jupiter:junit-jupiter-*:: in the list <ignoredUnusedDeclaredDependencies>

* :green_heart: Add skips and CI workflow
Fix #39
Add mvn site in workflow

* :see_no_evil: Add Git

* :pencil: Add gitmemory link

* :green_heart: Update maven-java-CI workflow (#41)

Fix #33 , #30 

* :green_heart: Update maven-java-CI workflow

* :green_heart: Delete mvn versions:set

* Rework du pom, sort et pluginManagement (#43)

* :fire: Reset pom.xml for a minimal one

* :heavy_plus_sign: Add dependencyManagement section

* :ok_hand:maven-antrun-plugin tasks to target

* :heavy_plus_sign: maven-enforcer-plugin
:pushpin: maven-site-plugin 3.9.0

* :recycle: Sort plugins in order execution

* :heavy_plus_sign: Add pluginManagement for jar project

* :sparkles: Finish new pom.xml

* Feature/enforcer and versions controls (#44)

* :heavy_plus_sign: Add versions-maven-plugin
Add new rules for maven-enforcer-plugin

* :hammer: Review pom before delete original

* :fire: Delete original pom

* :construction_worker: Add profile check project

* :books: Move links at the end in .md files

* Feature/issue 31 (#45)

* :ok_hand: Rework for maven-compiler-plugin

* :heavy_plus_sign: maven-surefire-report-plugin

* :ok_hand: Rework for maven-failsafe-plugin

* :ok_hand: Rework for maven-enforcer-plugin

* :ok_hand: Rework for git-commit-id-plugin

* :ok_hand_ Rework for maven-jar-plugin

* :heavy_plus_sign: maven-source-plugin
Fix #31

* :construction: Jacoco reports and Maven site

* :chart_with_upwards_trend: Fix coverage report inmaven site

* :fire: Remove "Java CI with Maven" workflow

diff --git a/.github/workflows/maven-java-CI.yml b/.github/workflows/maven-java-CI.yml
--- a/.github/workflows/maven-java-CI.yml
+++ b/.github/workflows/maven-java-CI.yml
@@ -3,26 +3,27 @@ name: Maven CI for Java
 on: [push]
 
 jobs:
-  get-context-info:
+  gihub-context-get-info:
     name: Get GitHub and Context informations
-    runs-on: ubuntu-18.04
+    runs-on: ubuntu-latest
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
-    # for debugging
-    - name: Dump env
-      run: |
-        env | sort
-    - name: Dump GitHub context
-      env:
-        GITHUB_CONTEXT: ${{ toJson(github) }}
-      run: echo "$GITHUB_CONTEXT"
-    - name: Dump job context
-      env:
-        JOB_CONTEXT: ${{ toJson(job) }}
-      run: echo "$JOB_CONTEXT"
+      - name: Checkout code
+        uses: actions/checkout@v2
+      # for debugging
+      - name: Dump env
+        run: |
+          env | sort
+      - name: Dump GitHub context
+        env:
+          GITHUB_CONTEXT: ${{ toJson(github) }}
+        run: echo "$GITHUB_CONTEXT"
+      - name: Dump job context
+        env:
+          JOB_CONTEXT: ${{ toJson(job) }}
+        run: echo "$JOB_CONTEXT"
 
-  build-test-package-deploy-maven:
+  maven-build-test-package-deploy-site:
+    name: Maven test, package and deploy Java project
     runs-on: ubuntu-latest
     steps:
       - name: Set up JDK 1.8
@@ -33,25 +34,65 @@ jobs:
         run: mvn -version
       - name: Check out from version control
         uses: actions/checkout@v2
+      - name: Cache Maven packages
+        uses: actions/cache@v1
+        env:
+          cache-name: cache-maven-dependencies
+        with:
+          path: ~/.m2/repository
+          key: ${{ runner.os }}-m2-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
+          restore-keys: |
+            ${{ runner.os }}-m2-${{ env.cache-name }}-
+            ${{ runner.os }}-m2-
+            ${{ runner.os }}-
       - name: Get groupId
         run: mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate '-Dexpression=project.groupId' -q -DforceStdout
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - name: Get artifactId
         run: mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate '-Dexpression=project.artifactId' -q -DforceStdout
       - name: Get version
+        id: build-version-initial
         run: mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate '-Dexpression=project.version' -q -DforceStdout
+      #TODEL - name: Get short SHA
+      #TODEL   id: short-sha
+      #TODEL   run: |
+      #TODEL     echo "Version initiale: ${MVN_VERSION}"
+      #TODEL     echo "::set-env name=COMMIT_ID_SHORT::${GITHUB_SHA::8}"
+      #TODEL - name: Create version number
+      #TODEL   id: create-version-number
+      #TODEL   uses: frabert/replace-string-action@v1.1
+      #TODEL   with:
+      #TODEL     pattern: "^(.*)-SNAPSHOT$"
+      #TODEL     string: ${{env.MVN_VERSION}}
+      #TODEL     replace-with: "$1-${COMMIT_ID_SHORT}-SNAPSHOT"
+      #TODEL - name: Set version number
+      #TODEL   run: |
+      #TODEL     echo "New version: ${{ steps.create-version-number.outputs.replaced }}"
+      #TODEL     mvn versions:set -DnewVersion=${{ steps.create-version-number.outputs.replaced }}
       - name: Build with Maven
-        run: mvn -U clean compile --file pom.xml
-      - name: Test with Maven
+        run: mvn -U clean compile -Pproject-controls-check --file pom.xml
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Unit Test with Maven
         run: mvn -U -Dmaven.main.skip test --file pom.xml
-      - name: Package with Maven
-        run: mvn -U -Dmaven.main.skip -Dmaven.test.skip=true verify --file pom.xml
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Verify with Maven
+        run: mvn -U -Dmaven.main.skip -Dunit.test.skip verify --file pom.xml
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       #TODO - name: Set Leak Period [SonarQube]
-        #run: checkout du parent commun
-        #run: mvn -U clean verify '-Dmaven.test.failure.ignore=true'
-        #run: mvn -U '-Dsonar.links.scm=http://gitxxx' '-Dsonar.links.ci=http://jenkinsxxx' org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar '-Dsonar.projectKey=[groupId]-[artifactId]' '-Dsonar.branch.name=develop' '-Dsonar.projectName=[artifactId]r' '-Dsonar.buildbreaker.skip=true' '-Dsonar.projectVersion=#d0b75832'
+      #run: checkout du parent commun
+      #run: mvn -U clean verify '-Dmaven.test.failure.ignore=true'
+      #run: mvn -U '-Dsonar.links.scm=http://gitxxx' '-Dsonar.links.ci=http://jenkinsxxx' org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar '-Dsonar.projectKey=[groupId]-[artifactId]' '-Dsonar.branch.name=develop' '-Dsonar.projectName=[artifactId]r' '-Dsonar.buildbreaker.skip=true' '-Dsonar.projectVersion=#d0b75832'
       #TODO - name: Quality Gate [SonarQube]
-        #run: mvn -U '-Dsonar.links.scm=http://gitxxx' '-Dsonar.links.ci=http://jenkinsxxx' org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar '-Dsonar.projectKey=[groupId]-[artifactId]' '-Dsonar.branch.name=develop' '-Dsonar.projectName=[artifactId]' '-Dsonar.gitlab.ref_name=b7c32ea3401d64f97eecc4dd46de331b00391cd7' '-Dsonar.gitlab.commit_sha=b7c32ea3401d64f97eecc4dd46de331b00391cd7' '-Dsonar.gitlab.project_id=3555'
+      #run: mvn -U '-Dsonar.links.scm=http://gitxxx' '-Dsonar.links.ci=http://jenkinsxxx' org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar '-Dsonar.projectKey=[groupId]-[artifactId]' '-Dsonar.branch.name=develop' '-Dsonar.projectName=[artifactId]' '-Dsonar.gitlab.ref_name=b7c32ea3401d64f97eecc4dd46de331b00391cd7' '-Dsonar.gitlab.commit_sha=b7c32ea3401d64f97eecc4dd46de331b00391cd7' '-Dsonar.gitlab.project_id=3555'
       - name: Publish to GitHub Packages Apache Maven
-        run: mvn -U -Dmaven.main.skip -Dmaven.test.skip=true deploy --file pom.xml
+        run: mvn -e -X -U -Dmaven.main.skip -Dunit.test.skip -Dintegration.test.skip deploy --file pom.xml
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Site with Maven
+        run: mvn -U site --file pom.xml
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
